events {
  worker_connections 1024;
}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
  }

  server {
    listen 80;
    server_name vhyxvoid.com api.vhyxvoid.com hub.vhyxvoid.com *.vhyxvoid.com;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 443 ssl;
    server_name api.vhyxvoid.com;

    ssl_certificate /etc/letsencrypt/live/api.vhyxvoid.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.vhyxvoid.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
      proxy_pass http://api:9000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }

  server {
    listen 443 ssl;
    server_name hub.vhyxvoid.com;

    ssl_certificate /etc/letsencrypt/live/api.vhyxvoid.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.vhyxvoid.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
      proxy_pass http://hub:9001;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;
      proxy_buffering off;
      proxy_cache off;
      tcp_nodelay on;
      proxy_socket_keepalive on;
      keepalive_timeout 3600s;
    }
  }

  server {
    listen 443 ssl;
    server_name *.vhyxvoid.com;

    ssl_certificate /etc/letsencrypt/live/vhyxvoid.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vhyxvoid.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    proxy_connect_timeout 10s;

    location / {
      proxy_pass http://hub:9001;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;
      proxy_buffering off; 
    }
  }
}
