// GET /admin/identity/audit-logs's real response shape, confirmed by
// reading admin.routes.ts directly AND via curl against the live local dev
// backend (real entries generated by Screens 3-5's own create/update/
// delete/assign actions). The response envelope is plain {success,
// message, data} -- NO total/count field anywhere, confirmed both by
// reading AdminAuditLogRepository (no countAll() exists at all; the three
// count-by-X methods that do exist are never called by the route handler)
// and by inspecting a real response body directly.
export type AdminAuditLogEntry = {
  id: string
  adminId: string
  action: string
  // AdminAuditLog.entities.ts's getActionDescription() falls back to the
  // raw action string for any action not in its internal map -- confirmed
  // live via a real 'admin.token_refreshed' entry (not in the map),
  // returned as-is rather than a formatted label. Render it as given, no
  // client-side re-formatting.
  actionDescription: string
  targetType: string
  targetId: string | null
  // Full before/after entity snapshots when present, NOT a field-level
  // diff -- confirmed via real entries (e.g. role.updated carries the
  // role's entire before and after state). Null for actions that don't
  // record one at all (confirmed via real entries: ability.deleted,
  // admin.login/logout/token_refreshed all have changes: null).
  changes: { before: unknown; after: unknown } | null
  // Present on some entries (ip/userAgent/statusCode), null on others --
  // confirmed via real entries that not every mutating route captures
  // request metadata into its audit log call (e.g. role.created/updated
  // via the UI's own dialog had metadata: null, while ability.deleted had
  // a real ip/userAgent/statusCode object). A real, pre-existing backend
  // inconsistency, not something to paper over in the UI.
  metadata: { ipAddress?: string; userAgent?: string; statusCode?: number; reason?: string } | null
  createdAt: string
}
