#!/usr/bin/env bash
# Regenerate cloudflare-ips.conf (nginx real_ip trust list) and
# cloudflare-allow.conf (origin allow-list geo map) from Cloudflare's
# published ranges. Run from the repo root, then reload nginx:
#   scripts/update-cloudflare-ips.sh && docker compose exec nginx nginx -s reload
set -euo pipefail

out="${1:-cloudflare-ips.conf}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by scripts/update-cloudflare-ips.sh from"
  echo "# https://www.cloudflare.com/ips-v4 and /ips-v6 - do not edit by hand."
  for family in v4 v6; do
    ranges="$(curl -fsS --max-time 15 "https://www.cloudflare.com/ips-$family")"
    [ -n "$ranges" ] || { echo "empty response for ips-$family" >&2; exit 1; }
    while read -r cidr; do
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done <<<"$ranges"
  done
  # Connections reach nginx's HTTPS servers through the local SNI router
  # (nginx.conf, stream block). Safe to trust: the origin lock below only
  # lets requests through whose PROXY-protocol address is Cloudflare's.
  echo "set_real_ip_from 127.0.0.1;"
  echo "real_ip_header CF-Connecting-IP;"
} >"$tmp"

mv "$tmp" "$out"
chmod 644 "$out"
echo "wrote $out ($(grep -c set_real_ip_from "$out") ranges)"

# Same ranges as a geo map keyed on the client address the SNI router passes
# with the PROXY protocol (the TCP peer seen by nginx itself is 127.0.0.1).
# allow/deny can't be used for this: real_ip rewrites $remote_addr.
allow_out="$(dirname "$out")/cloudflare-allow.conf"
{
  echo "# Generated by scripts/update-cloudflare-ips.sh from $(basename "$out") - do not edit by hand."
  echo "geo \$proxy_protocol_addr \$from_cloudflare {"
  echo "  default 0;"
  grep -v '127.0.0.1' "$out" | sed -n 's/^set_real_ip_from \(.*\);$/  \1 1;/p'
  echo "}"
} >"$allow_out"
chmod 644 "$allow_out"
echo "wrote $allow_out"
