#!/usr/bin/env bash
# Regenerate cloudflare-ips.conf (nginx real_ip trust list) from Cloudflare's
# published ranges. Run from the repo root, then reload nginx:
#   scripts/update-cloudflare-ips.sh && docker compose exec nginx nginx -s reload
set -euo pipefail

out="${1:-cloudflare-ips.conf}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by scripts/update-cloudflare-ips.sh from"
  echo "# https://www.cloudflare.com/ips-v4 and /ips-v6 - do not edit by hand."
  for family in v4 v6; do
    ranges="$(curl -fsS --max-time 15 "https://www.cloudflare.com/ips-$family")"
    [ -n "$ranges" ] || { echo "empty response for ips-$family" >&2; exit 1; }
    while read -r cidr; do
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done <<<"$ranges"
  done
  echo "real_ip_header CF-Connecting-IP;"
} >"$tmp"

mv "$tmp" "$out"
chmod 644 "$out"
echo "wrote $out ($(grep -c set_real_ip_from "$out") ranges)"
