#!/usr/bin/env bash
# Regenerate cloudflare-ips.conf (nginx real_ip trust list) and
# cloudflare-allow.conf (origin allow-list geo map) from Cloudflare's
# published ranges. Run from the repo root, then reload nginx:
#   scripts/update-cloudflare-ips.sh && docker compose exec nginx nginx -s reload
set -euo pipefail

out="${1:-cloudflare-ips.conf}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by scripts/update-cloudflare-ips.sh from"
  echo "# https://www.cloudflare.com/ips-v4 and /ips-v6 - do not edit by hand."
  for family in v4 v6; do
    ranges="$(curl -fsS --max-time 15 "https://www.cloudflare.com/ips-$family")"
    [ -n "$ranges" ] || { echo "empty response for ips-$family" >&2; exit 1; }
    while read -r cidr; do
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done <<<"$ranges"
  done
  echo "real_ip_header CF-Connecting-IP;"
} >"$tmp"

mv "$tmp" "$out"
chmod 644 "$out"
echo "wrote $out ($(grep -c set_real_ip_from "$out") ranges)"

# Same ranges as a geo map keyed on the original TCP peer. allow/deny can't be
# used for this: real_ip rewrites $remote_addr to the visitor's IP, so it would
# reject every proxied request. $realip_remote_addr is the pre-rewrite peer.
allow_out="$(dirname "$out")/cloudflare-allow.conf"
{
  echo "# Generated by scripts/update-cloudflare-ips.sh from $(basename "$out") - do not edit by hand."
  echo "geo \$realip_remote_addr \$from_cloudflare {"
  echo "  default 0;"
  sed -n 's/^set_real_ip_from \(.*\);$/  \1 1;/p' "$out"
  echo "}"
} >"$allow_out"
chmod 644 "$allow_out"
echo "wrote $allow_out"
